[build]
  command = "npm run build"  # Adjust based on your build script
  publish = "public"         # Adjust based on your publish directory
  functions = "netlify/functions"  # Adjust based on your functions directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
